SET
REFERENTIAL_INTEGRITY FALSE;

-- IT'S IMPORTANT TO RESTART PK AUTOINCREMENT OTHERWISE IT WOULDN'T RESET ITSELF
TRUNCATE TABLE role RESTART IDENTITY;
TRUNCATE TABLE account RESTART IDENTITY;
TRUNCATE TABLE profile RESTART IDENTITY;
TRUNCATE TABLE anime RESTART IDENTITY;
TRUNCATE TABLE profile_anime RESTART IDENTITY;

SET
REFERENTIAL_INTEGRITY TRUE;

